
import { GoogleGenerativeAI } from "@google/generative-ai";
import { SlideAnalysis } from "@/types";

export const regenerateSlide = async (
    apiKey: string,
    originalImage: string | undefined,
    title: string,
    keyData: string[],
    analysis: SlideAnalysis
): Promise<string> => {
    const genAI = new GoogleGenerativeAI(apiKey);

    // Attempt to use the model the user originally had, or a known image-capable one.
    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash-exp" });

    const prompt = `
    Create a presentation slide based on the following specifications.
    
    1. Main Title: "${title}"
    2. Key Points:
    ${keyData.map((k, i) => `  - ${k}`).join('\n')}
    
    Style Instructions:
    - Theme: ${analysis.design_context.theme}
    - Fonts: ${analysis.design_context.font_characteristics}
    - Layout: Professional, aligned, clean.
    - Background: Enhance the provided image or generate a matching style.
    
    Output:
    Return a high-quality IMAGE of the slide.
  `;

    const parts: any[] = [{ text: prompt }];

    if (originalImage) {
        const base64Data = originalImage.split(",")[1];
        parts.push({
            inlineData: {
                data: base64Data,
                mimeType: "image/png",
            },
        });
    }

    try {
        // NOTE: As of now, returning images directly via `generateContent` in the JS SDK 
        // requires specific handling of 'inlineData' in the response.
        const result = await model.generateContent(parts);
        const response = await result.response;

        // Check for executable code (if checking for diagrams) or images
        // For now, if the model outputs an image, it usually comes in `candidates[0].content.parts[0].inlineData`
        // depending on the API version.

        const partsResponse = response.candidates?.[0]?.content?.parts;
        if (partsResponse) {
            for (const part of partsResponse) {
                if (part.inlineData && part.inlineData.mimeType.startsWith("image")) {
                    return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                }
            }
        }

        throw new Error("No image generated by the AI. Please try again or select a clearer model.");

    } catch (e) {
        console.error("Regeneration Error:", e);
        throw e;
    }
};
